export const QUIZ_TOPICS = [
  { id: 'solar-system', name: '太阳系', icon: '☀️', skin: 'flame', skinName: '烈焰陨石', skinColor: '#ff6b35' },
  { id: 'stellar-evolution', name: '恒星演化', icon: '⭐', skin: 'stellar', skinName: '星核陨石', skinColor: '#ffd700' },
  { id: 'galaxy-universe', name: '星系与宇宙', icon: '🌌', skin: 'deep', skinName: '深空陨石', skinColor: '#4a9eff' },
  { id: 'space-exploration', name: '航天探索史', icon: '🚀', skin: 'pioneer', skinName: '先驱陨石', skinColor: '#a8ff78' },
  { id: 'astronomical-observation', name: '天文观测', icon: '🔭', skin: 'crystal', skinName: '晶眸陨石', skinColor: '#e0c3fc' },
  { id: 'astrophysics', name: '宇宙物理', icon: '⚛️', skin: 'quantum', skinName: '量子陨石', skinColor: '#ff9a9e' },
];

export const DIFFICULTIES = [
  { key: 'easy', name: '初级', pass: 9, total: 12 },
  { key: 'medium', name: '中级', pass: 9, total: 12 },
  { key: 'hard', name: '高级', pass: 9, total: 12 },
];

export const QUIZ_QUESTIONS = [
  // ============ 太阳系 - 初级 ============
  { id: 'ss-easy-001', topic: 'solar-system', difficulty: 'easy', q: '太阳系中最大的行星是？', opts: ['土星', '木星', '天王星', '海王星'], ans: 1, explanation: '木星是太阳系最大的行星,质量约为地球的318倍。' },
  { id: 'ss-easy-002', topic: 'solar-system', difficulty: 'easy', q: '太阳系中距离太阳最近的行星是？', opts: ['金星', '水星', '火星', '地球'], ans: 1, explanation: '水星是离太阳最近的行星,平均距离约5800万公里。' },
  { id: 'ss-easy-003', topic: 'solar-system', difficulty: 'easy', q: '光从太阳到达地球大约需要多长时间？', opts: ['8分钟', '80分钟', '8秒', '8小时'], ans: 0, explanation: '太阳到地球约1.5亿公里,光速传播约8分20秒。' },
  { id: 'ss-easy-004', topic: 'solar-system', difficulty: 'easy', q: '月球绕地球公转一周大约需要多少天？', opts: ['7天', '14天', '27天', '30天'], ans: 2, explanation: '月球公转周期约27.3天(恒星月)。' },
  { id: 'ss-easy-005', topic: 'solar-system', difficulty: 'easy', q: '以下哪颗不是太阳系的八大行星之一？', opts: ['水星', '冥王星', '金星', '火星'], ans: 1, explanation: '冥王星于2006年被重新归类为矮行星。' },
  { id: 'ss-easy-006', topic: 'solar-system', difficulty: 'easy', q: '地球的天然卫星是？', opts: ['火卫一', '月球', '木卫二', '土卫六'], ans: 1, explanation: '月球是地球唯一的天然卫星。' },
  { id: 'ss-easy-007', topic: 'solar-system', difficulty: 'easy', q: '被称为"红色行星"的是？', opts: ['金星', '水星', '火星', '木星'], ans: 2, explanation: '火星表面富含氧化铁,呈现红色。' },
  { id: 'ss-easy-008', topic: 'solar-system', difficulty: 'easy', q: '太阳系中拥有最壮观光环的行星是？', opts: ['木星', '土星', '天王星', '海王星'], ans: 1, explanation: '土星的光环由冰和岩石碎片组成,极为显著。' },
  { id: 'ss-easy-009', topic: 'solar-system', difficulty: 'easy', q: '一年有约365天是因为？', opts: ['地球自转一周', '地球绕太阳公转一周', '月球绕地球一周', '太阳自转一周'], ans: 1, explanation: '地球公转周期约365.25天。' },
  { id: 'ss-easy-010', topic: 'solar-system', difficulty: 'easy', q: '一天有24小时是因为？', opts: ['地球自转一周', '地球公转一周', '月相变化', '太阳活动'], ans: 0, explanation: '地球自转一周约24小时,形成昼夜更替。' },
  { id: 'ss-easy-011', topic: 'solar-system', difficulty: 'easy', q: '太阳的主要成分是？', opts: ['岩石', '氢和氦', '铁', '水'], ans: 1, explanation: '太阳约74%氢、24%氦,核聚变释放能量。' },
  { id: 'ss-easy-012', topic: 'solar-system', difficulty: 'easy', q: '太阳系外缘的小行星密集带位于哪两颗行星之间？', opts: ['地球与火星', '火星与木星', '木星与土星', '土星与天王星'], ans: 1, explanation: '主小行星带位于火星和木星轨道之间。' },
  { id: 'ss-easy-013', topic: 'solar-system', difficulty: 'easy', q: '太阳系中体积最大的卫星是？', opts: ['月球', '木卫三', '土卫六', '木卫四'], ans: 1, explanation: '木卫三(甘尼米德)直径约5268公里,比水星还大。' },
  { id: 'ss-easy-014', topic: 'solar-system', difficulty: 'easy', q: '哈雷彗星回归周期约为？', opts: ['约76年', '约36年', '约150年', '约5年'], ans: 0, explanation: '哈雷彗星周期约76年,上次回归是1986年。' },
  { id: 'ss-easy-015', topic: 'solar-system', difficulty: 'easy', q: '地球大气层中含量最多的气体是？', opts: ['氧气', '二氧化碳', '氮气', '氩气'], ans: 2, explanation: '氮气约占大气78%,氧气约占21%。' },

  // ============ 太阳系 - 中级 ============
  { id: 'ss-medium-001', topic: 'solar-system', difficulty: 'medium', q: '太阳系中自转最快的行星是？', opts: ['木星', '地球', '火星', '水星'], ans: 0, explanation: '木星自转一周仅约9小时55分,是八大行星中最快的。' },
  { id: 'ss-medium-002', topic: 'solar-system', difficulty: 'medium', q: '金星上的一天比一年还长,这是因为？', opts: ['金星距离太阳很近', '金星自转极慢且方向相反', '金星没有大气', '金星轨道是椭圆形'], ans: 1, explanation: '金星自转周期约243天,公转约225天,且自转方向与多数行星相反。' },
  { id: 'ss-medium-003', topic: 'solar-system', difficulty: 'medium', q: '哪颗行星拥有太阳系中最大的火山？', opts: ['地球', '金星', '火星', '水星'], ans: 2, explanation: '火星上的奥林帕斯山高约21公里,是太阳系最大的火山。' },
  { id: 'ss-medium-004', topic: 'solar-system', difficulty: 'medium', q: '木星的"大红斑"是什么？', opts: ['一座巨大火山', '一场持续数百年的反气旋风暴', '一片陨石坑', '一个引力异常区域'], ans: 1, explanation: '大红斑是木星上一个持续至少350年的巨大反气旋风暴。' },
  { id: 'ss-medium-005', topic: 'solar-system', difficulty: 'medium', q: '柯伊伯带主要位于哪里？', opts: ['火星轨道附近', '海王星轨道之外', '木星轨道内侧', '太阳与水星之间'], ans: 1, explanation: '柯伊伯带位于海王星轨道之外,是众多冰质天体的家园。' },
  { id: 'ss-medium-006', topic: 'solar-system', difficulty: 'medium', q: '土卫六(泰坦)的特别之处在于？', opts: ['它是唯一拥有浓厚大气的卫星', '它会发光', '它比月球大10倍', '它有金属表面'], ans: 0, explanation: '土卫六是唯一拥有浓厚大气层的卫星,主要由氮气组成。' },
  { id: 'ss-medium-007', topic: 'solar-system', difficulty: 'medium', q: '太阳的核聚变主要发生在哪里？', opts: ['表面', '日冕', '核心', '光球层'], ans: 2, explanation: '太阳的核心温度高达1500万K,氢核聚变为氦释放能量。' },
  { id: 'ss-medium-008', topic: 'solar-system', difficulty: 'medium', q: '太阳黑子是？', opts: ['太阳上的大型陨石坑', '太阳表面温度较低的区域', '太阳爆发的火山', '太阳磁场断裂'], ans: 1, explanation: '黑子是磁场强烈、温度比周围低约1500K的区域,因而显得较暗。' },
  { id: 'ss-medium-009', topic: 'solar-system', difficulty: 'medium', q: '行星轨道开普勒第三定律描述的是？', opts: ['行星轨道是椭圆', '相同时间扫过相同面积', '公转周期平方与轨道半长轴立方成正比', '所有行星速度相同'], ans: 2, explanation: '开普勒第三定律:T²∝a³,公转周期的平方与轨道半长轴的立方成正比。' },
  { id: 'ss-medium-010', topic: 'solar-system', difficulty: 'medium', q: '木卫二(欧罗巴)被认为可能存在生命的原因是？', opts: ['表面有大气', '冰壳下可能存在液态海洋', '靠近太阳', '有火山活动'], ans: 1, explanation: '木卫二冰壳下被推测有液态水海洋,是地外生命候选地之一。' },
  { id: 'ss-medium-011', topic: 'solar-system', difficulty: 'medium', q: '海王星被发现的方式是？', opts: ['偶然观测', '通过对天王星轨道扰动的预测', '哈勃望远镜发现', '探测器拍摄'], ans: 1, explanation: '勒维耶根据天王星轨道异常预测了海王星位置,1846年被观测证实。' },
  { id: 'ss-medium-012', topic: 'solar-system', difficulty: 'medium', q: '"地球的姐妹星"通常指？', opts: ['火星', '金星', '水星', '月球'], ans: 1, explanation: '金星与地球大小、质量、组成相近,被称为地球的姐妹星。' },
  { id: 'ss-medium-013', topic: 'solar-system', difficulty: 'medium', q: '矮行星谷神星位于？', opts: ['柯伊伯带', '主小行星带', '太阳与水星之间', '海王星轨道外'], ans: 1, explanation: '谷神星是主小行星带中最大的天体,被归为矮行星。' },
  { id: 'ss-medium-014', topic: 'solar-system', difficulty: 'medium', q: '日冕最显著时通常出现在什么时候？', opts: ['日落时', '满月时', '日全食时', '日出时'], ans: 2, explanation: '日全食时月球遮住光球,日冕的暗弱光辉才容易被肉眼看到。' },
  { id: 'ss-medium-015', topic: 'solar-system', difficulty: 'medium', q: '太阳风的主要成分是？', opts: ['中子', '光子', '带电粒子(质子和电子)', '岩石碎片'], ans: 2, explanation: '太阳风是从日冕喷出的高速带电粒子流,以质子和电子为主。' },

  // ============ 太阳系 - 高级 ============
  { id: 'ss-hard-001', topic: 'solar-system', difficulty: 'hard', q: '罗氏极限描述的是？', opts: ['卫星因潮汐力被撕裂的最近距离', '行星最大轨道', '光不能逃脱的距离', '地球磁层边界'], ans: 0, explanation: '罗氏极限是天体被主星潮汐力解体的临界距离,土星环可能源于此。' },
  { id: 'ss-hard-002', topic: 'solar-system', difficulty: 'hard', q: '木星的伽利略卫星不包括？', opts: ['木卫一(伊奥)', '木卫二(欧罗巴)', '木卫三(甘尼米德)', '土卫六(泰坦)'], ans: 3, explanation: '伽利略1610年发现的四颗木卫:伊奥、欧罗巴、甘尼米德、卡里斯托。' },
  { id: 'ss-hard-003', topic: 'solar-system', difficulty: 'hard', q: '日球层顶(Heliopause)指的是？', opts: ['太阳光球层边缘', '太阳风与星际介质压力平衡的边界', '行星轨道最远处', '太阳系黑洞边界'], ans: 1, explanation: '日球层顶是太阳风与星际介质压力达到平衡的边界,旅行者1号已穿越。' },
  { id: 'ss-hard-004', topic: 'solar-system', difficulty: 'hard', q: '小行星带没有形成行星的主要原因是？', opts: ['物质太少', '木星引力扰动', '距离太阳太远', '碰撞频繁'], ans: 1, explanation: '木星强大引力阻止了主带物质聚合成行星。' },
  { id: 'ss-hard-005', topic: 'solar-system', difficulty: 'hard', q: '金星表面温度比水星更高的主要原因是？', opts: ['离太阳更近', '没有自转', '浓密的二氧化碳大气产生强烈温室效应', '内部熔岩活动'], ans: 2, explanation: '金星96.5% CO₂大气产生剧烈温室效应,表面温度可达462°C。' },
  { id: 'ss-hard-006', topic: 'solar-system', difficulty: 'hard', q: '太阳系中拉格朗日点 L1、L2、L3 都是？', opts: ['稳定平衡点', '不稳定平衡点', '黑洞', '行星轨道交点'], ans: 1, explanation: 'L1/L2/L3 是不稳定平衡点,L4/L5 是稳定的。詹姆斯·韦伯位于日地L2。' },
  { id: 'ss-hard-007', topic: 'solar-system', difficulty: 'hard', q: '土卫二(恩克拉多斯)南极喷出的羽流主要由什么组成？', opts: ['甲烷', '水冰和盐分', '氨气', '岩石粉尘'], ans: 1, explanation: '土卫二南极喷流含水冰和盐分,提示冰下存在液态海洋。' },
  { id: 'ss-hard-008', topic: 'solar-system', difficulty: 'hard', q: '太阳的日震学(Helioseismology)研究的是？', opts: ['太阳地震', '太阳内部振荡模式以推断结构', '太阳黑子周期', '日冕加热'], ans: 1, explanation: '日震学通过观测太阳表面振荡反演内部结构,如同地震波探查地球。' },
  { id: 'ss-hard-009', topic: 'solar-system', difficulty: 'hard', q: '彗星的两条尾巴中,通常较直且呈蓝色的是？', opts: ['尘埃尾', '离子尾', '钠尾', '反尾'], ans: 1, explanation: '离子尾因太阳风电离作用呈直线状蓝色;尘埃尾较弯曲呈白色。' },
  { id: 'ss-hard-010', topic: 'solar-system', difficulty: 'hard', q: '海王星上层大气的甲烷使其呈何种颜色？', opts: ['红色', '蓝色', '绿色', '黄色'], ans: 1, explanation: '海王星大气中的甲烷强烈吸收红光,反射蓝光使其呈深蓝色。' },
  { id: 'ss-hard-011', topic: 'solar-system', difficulty: 'hard', q: '天王星的自转轴倾角约为？', opts: ['23°', '45°', '98°', '0°'], ans: 2, explanation: '天王星倾角约98°,几乎"躺"着自转,可能源于早期巨大撞击。' },
  { id: 'ss-hard-012', topic: 'solar-system', difficulty: 'hard', q: '奥尔特云被认为是？', opts: ['火星卫星残骸', '太阳系最外围的彗星储库', '银河系中心结构', '行星形成失败区'], ans: 1, explanation: '奥尔特云距太阳约2000-200000 AU,为长周期彗星的来源。' },
  { id: 'ss-hard-013', topic: 'solar-system', difficulty: 'hard', q: '行星的"霜线"(Frost Line)是指？', opts: ['行星表面冰盖边界', '原行星盘中挥发物可凝结成冰的距离', '彗星的尾巴边界', '日地轨道交点'], ans: 1, explanation: '霜线之外水、甲烷等可凝结为冰,影响类地行星与气态巨行星的分布。' },
  { id: 'ss-hard-014', topic: 'solar-system', difficulty: 'hard', q: '水星轨道的近日点进动现象主要由什么解释？', opts: ['牛顿引力', '广义相对论', '量子修正', '太阳风扰动'], ans: 1, explanation: '水星近日点每世纪多进动约43角秒,爱因斯坦广义相对论给出精确解释。' },
  { id: 'ss-hard-015', topic: 'solar-system', difficulty: 'hard', q: '木卫一(伊奥)成为太阳系火山活动最剧烈天体的原因是？', opts: ['内部放射性元素丰富', '木星与其他卫星的潮汐加热', '太阳辐射加热', '大气层保温'], ans: 1, explanation: '木卫一受木星与其他伽利略卫星共振潮汐加热,内部熔融剧烈喷发。' },

  // ============ 恒星演化 - 初级 ============
  { id: 'se-easy-001', topic: 'stellar-evolution', difficulty: 'easy', q: '恒星的能量主要来自？', opts: ['化学燃烧', '核聚变', '引力收缩', '电流'], ans: 1, explanation: '恒星核心通过氢核聚变成氦释放巨大能量。' },
  { id: 'se-easy-002', topic: 'stellar-evolution', difficulty: 'easy', q: '恒星诞生于什么样的环境？', opts: ['黑洞', '星云中的气体和尘埃', '行星表面', '宇宙真空'], ans: 1, explanation: '恒星形成于分子云的引力坍缩区域。' },
  { id: 'se-easy-003', topic: 'stellar-evolution', difficulty: 'easy', q: '太阳目前处于哪个演化阶段？', opts: ['原恒星', '主序星', '红巨星', '白矮星'], ans: 1, explanation: '太阳已经在主序阶段稳定燃烧约46亿年。' },
  { id: 'se-easy-004', topic: 'stellar-evolution', difficulty: 'easy', q: '恒星的颜色与什么有关？', opts: ['年龄', '表面温度', '距离', '质量唯一'], ans: 1, explanation: '蓝色恒星温度高,红色恒星温度低,反映表面温度。' },
  { id: 'se-easy-005', topic: 'stellar-evolution', difficulty: 'easy', q: '白矮星是什么？', opts: ['年轻恒星', '中等质量恒星演化末期的致密残骸', '黑洞', '行星'], ans: 1, explanation: '中低质量恒星抛掉外壳后留下的高密度核心。' },
  { id: 'se-easy-006', topic: 'stellar-evolution', difficulty: 'easy', q: '比太阳质量大很多的恒星最终可能形成？', opts: ['白矮星', '黑洞或中子星', '彗星', '行星'], ans: 1, explanation: '大质量恒星超新星爆发后留下中子星或黑洞。' },
  { id: 'se-easy-007', topic: 'stellar-evolution', difficulty: 'easy', q: '"天狼星"是夜空中最亮的恒星,它属于哪个星座？', opts: ['猎户座', '大犬座', '狮子座', '天蝎座'], ans: 1, explanation: '天狼星(Sirius)是大犬座α星,夜空最亮恒星。' },
  { id: 'se-easy-008', topic: 'stellar-evolution', difficulty: 'easy', q: '红巨星阶段的恒星有什么特点？', opts: ['体积巨大、表面温度低', '体积小、温度高', '不发光', '含金属多'], ans: 0, explanation: '主序后核外壳膨胀,表面温度降低,体积膨胀至原来数十至数百倍。' },
  { id: 'se-easy-009', topic: 'stellar-evolution', difficulty: 'easy', q: '银河系中绝大多数恒星处于哪个阶段？', opts: ['原恒星', '主序', '超新星', '白矮星'], ans: 1, explanation: '主序阶段最长,因此大多数恒星都处于主序阶段。' },
  { id: 'se-easy-010', topic: 'stellar-evolution', difficulty: 'easy', q: '北极星目前指的是哪颗恒星？', opts: ['天狼星', '勾陈一(小熊座α)', '织女星', '南门二'], ans: 1, explanation: '当前北极星是小熊座α星(勾陈一),由于岁差北极星会变化。' },
  { id: 'se-easy-011', topic: 'stellar-evolution', difficulty: 'easy', q: '太阳的预期寿命大约是？', opts: ['10亿年', '约100亿年', '1万亿年', '1亿年'], ans: 1, explanation: '太阳总寿命约100亿年,目前已度过约一半。' },
  { id: 'se-easy-012', topic: 'stellar-evolution', difficulty: 'easy', q: '恒星亮度的视星等数值越小代表？', opts: ['越暗', '越亮', '越远', '越近'], ans: 1, explanation: '视星等数值越小越亮,负值代表非常亮的天体。' },
  { id: 'se-easy-013', topic: 'stellar-evolution', difficulty: 'easy', q: '组成宇宙中恒星的最主要元素是？', opts: ['碳', '氢', '铁', '氧'], ans: 1, explanation: '宇宙中约75%(质量比)的物质是氢,恒星主要由氢构成。' },
  { id: 'se-easy-014', topic: 'stellar-evolution', difficulty: 'easy', q: '猎户座中那颗肉眼可见的红色巨星叫？', opts: ['参宿七', '参宿四', '北河三', '毕宿五'], ans: 1, explanation: '参宿四(Betelgeuse)是猎户座α,红超巨星。' },
  { id: 'se-easy-015', topic: 'stellar-evolution', difficulty: 'easy', q: '双星系统是指？', opts: ['两颗行星', '两颗恒星因引力束缚相互绕转', '两颗卫星', '一颗恒星和一颗黑洞不可能共存'], ans: 1, explanation: '双星由两颗恒星互相绕共同质心运动构成。' },

  // ============ 恒星演化 - 中级 ============
  { id: 'se-medium-001', topic: 'stellar-evolution', difficulty: 'medium', q: '赫罗图(H-R 图)的横纵坐标分别是？', opts: ['年龄与质量', '光度(或绝对星等)与温度(或光谱型)', '距离与颜色', '质量与大小'], ans: 1, explanation: '赫罗图以光度对温度作图,主序、巨星支、白矮星等清晰可辨。' },
  { id: 'se-medium-002', topic: 'stellar-evolution', difficulty: 'medium', q: '光谱型 O B A F G K M 中,温度最高的是？', opts: ['M', 'G', 'O', 'F'], ans: 2, explanation: 'O 型最热(>30000K),M 型最冷(<3700K)。太阳是 G 型。' },
  { id: 'se-medium-003', topic: 'stellar-evolution', difficulty: 'medium', q: '主序星核心进行的核反应主要是？', opts: ['氦聚变', '质子-质子链与CNO循环将氢聚变为氦', '碳燃烧', '硅燃烧'], ans: 1, explanation: '太阳类恒星以pp链为主,大质量恒星以CNO循环为主。' },
  { id: 'se-medium-004', topic: 'stellar-evolution', difficulty: 'medium', q: '钱德拉塞卡极限约为多少倍太阳质量?它指的是？', opts: ['1.4,白矮星质量上限', '3,中子星上限', '8,主序下限', '20,黑洞下限'], ans: 0, explanation: '约1.4倍太阳质量是电子简并压可支撑白矮星的极限。' },
  { id: 'se-medium-005', topic: 'stellar-evolution', difficulty: 'medium', q: '行星状星云的来源是？', opts: ['超新星爆发', '中低质量恒星演化末期抛射的外壳', '黑洞吞噬', '星际碰撞'], ans: 1, explanation: '红巨星阶段抛射外层气体被中心白矮星电离形成行星状星云。' },
  { id: 'se-medium-006', topic: 'stellar-evolution', difficulty: 'medium', q: '超新星 Ia 型的爆发机制通常被认为是？', opts: ['大质量恒星核坍缩', '白矮星吸积或合并达到钱德拉塞卡极限引发热核爆炸', '黑洞合并', '行星碰撞'], ans: 1, explanation: 'Ia 型由白矮星热核失控引爆,光度标准化使其成为"标准烛光"。' },
  { id: 'se-medium-007', topic: 'stellar-evolution', difficulty: 'medium', q: '中子星的密度大约相当于？', opts: ['水的1000倍', '原子核密度', '黑洞', '太阳平均密度'], ans: 1, explanation: '中子星密度可达10¹⁷ kg/m³,接近原子核密度。' },
  { id: 'se-medium-008', topic: 'stellar-evolution', difficulty: 'medium', q: '"脉冲星"实际上是？', opts: ['脉动变星', '高速自转并发射定向射电束的中子星', '伴星周期遮蔽', '黑洞辐射'], ans: 1, explanation: '脉冲星因自转使射电束周期性扫过地球,1967年贝尔首次发现。' },
  { id: 'se-medium-009', topic: 'stellar-evolution', difficulty: 'medium', q: '造父变星的重要意义是？', opts: ['寻找系外行星', '通过周期-光度关系测量距离', '探测黑洞', '确定恒星年龄'], ans: 1, explanation: '勒维特发现造父变星周期-光度关系,成为测距标尺。' },
  { id: 'se-medium-010', topic: 'stellar-evolution', difficulty: 'medium', q: '主序阶段恒星的寿命与质量的关系是？', opts: ['质量越大寿命越长', '质量越大寿命越短', '无关', '只与金属丰度有关'], ans: 1, explanation: '高质量恒星核反应剧烈,寿命短(几百万年),低质量可达上千亿年。' },
  { id: 'se-medium-011', topic: 'stellar-evolution', difficulty: 'medium', q: '"褐矮星"是？', opts: ['失败的恒星,质量不足以稳定氢聚变', '冷却的白矮星', '红巨星残骸', '小型黑洞'], ans: 0, explanation: '褐矮星质量约13-80木星质量,无法持续氢聚变,只能氘燃烧。' },
  { id: 'se-medium-012', topic: 'stellar-evolution', difficulty: 'medium', q: '太阳大约50亿年后会经历什么主要阶段?', opts: ['超新星爆发→黑洞', '红巨星→行星状星云→白矮星', '直接消失', '脉冲星化'], ans: 1, explanation: '太阳质量较低,演化路径为红巨星→抛射外壳→白矮星(碳氧)。' },
  { id: 'se-medium-013', topic: 'stellar-evolution', difficulty: 'medium', q: '"金属丰度"在天文学中指的是？', opts: ['恒星含金属比例', '比氢氦重的元素的相对比例', '磁场强度', '光度等级'], ans: 1, explanation: '天文学称比氦重的元素为"金属",衡量化学演化历史。' },
  { id: 'se-medium-014', topic: 'stellar-evolution', difficulty: 'medium', q: 'HII 区是什么？', opts: ['黑洞周围吸积盘', '被年轻大质量恒星电离的氢气区域', '冷分子云', '白矮星残骸'], ans: 1, explanation: 'HII 区是被强紫外辐射电离的氢区,常见于恒星形成区(如猎户星云)。' },
  { id: 'se-medium-015', topic: 'stellar-evolution', difficulty: 'medium', q: '原恒星向主序演化的"赫氏前主序轨迹"中,初期主要靠什么发光？', opts: ['核聚变', '引力收缩释放的势能(开尔文-赫姆霍兹机制)', '化学反应', '中微子'], ans: 1, explanation: '主序前阶段核反应未点燃,主要靠引力势能转化为热辐射。' },

  // ============ 恒星演化 - 高级 ============
  { id: 'se-hard-001', topic: 'stellar-evolution', difficulty: 'hard', q: '托尔曼-奥本海默-沃尔科夫(TOV)极限大约是？', opts: ['1.4 M☉', '约 2-3 M☉,中子星质量上限', '8 M☉,主序下限', '20 M☉'], ans: 1, explanation: 'TOV极限是中子简并压维持中子星的上限,超过则坍缩为黑洞。' },
  { id: 'se-hard-002', topic: 'stellar-evolution', difficulty: 'hard', q: '大质量恒星核心元素合成至何种元素后会触发核坍缩超新星？', opts: ['碳', '氧', '硅,最终在核心积累铁', '钙'], ans: 2, explanation: '硅燃烧生成铁,铁聚变吸热使核心失去支撑,引发坍缩。' },
  { id: 'se-hard-003', topic: 'stellar-evolution', difficulty: 'hard', q: 'r-过程(快中子俘获)主要发生在？', opts: ['太阳内部', '中子星合并和某些超新星中', '红巨星表面', '白矮星'], ans: 1, explanation: 'r-过程在极强中子流环境中合成重元素(如金、铂),GW170817证实双中子星合并是源之一。' },
  { id: 'se-hard-004', topic: 'stellar-evolution', difficulty: 'hard', q: '渐近巨星支(AGB)恒星的核心结构是？', opts: ['氢核', '氦核', '碳氧核外包氦壳与氢壳燃烧层', '中子核'], ans: 2, explanation: 'AGB 阶段恒星核心为简并碳氧,外包氦壳与氢壳交替燃烧,产生热脉冲。' },
  { id: 'se-hard-005', topic: 'stellar-evolution', difficulty: 'hard', q: '沃尔夫-拉叶星(WR)的特征是？', opts: ['冷红巨星', '高温、强烈星风、暴露氦或更深核', '低光度白矮星', '原恒星'], ans: 1, explanation: 'WR 星因强星风剥离外层,显示氦/碳/氮发射线,是大质量恒星晚期。' },
  { id: 'se-hard-006', topic: 'stellar-evolution', difficulty: 'hard', q: '恒星形成的"金斯不稳定性"取决于？', opts: ['只有质量', '云团质量、温度与密度的平衡', '光度', '化学组成唯一'], ans: 1, explanation: '当质量超过金斯质量(取决于温度密度),云团引力胜出开始坍缩。' },
  { id: 'se-hard-007', topic: 'stellar-evolution', difficulty: 'hard', q: '对极超新星(超亮超新星)可能与什么物理机制有关？', opts: ['普通核坍缩', '磁星驱动或对不稳定性(pair-instability)', '白矮星吸积', '行星撞击'], ans: 1, explanation: '极亮超新星可由强磁化中子星(磁星)能量注入或对不稳定爆炸解释。' },
  { id: 'se-hard-008', topic: 'stellar-evolution', difficulty: 'hard', q: '中子星的"冰山"结构通常包括？', opts: ['外壳—内壳—外核—内核', '只有铁壳', '只有等离子', '冰盖'], ans: 0, explanation: '中子星结构分外壳(原子核晶格)、内壳(中子滴出)、外核(中子流体)、内核(可能夸克物质)。' },
  { id: 'se-hard-009', topic: 'stellar-evolution', difficulty: 'hard', q: 'X射线双星中, "Roche 瓣溢流"指的是？', opts: ['黑洞辐射', '伴星填满洛希瓣物质流向致密天体', '超新星抛射', '潮汐撕碎事件'], ans: 1, explanation: '主星扩张充满洛希瓣后通过 L1 点向伴星流入物质形成吸积盘。' },
  { id: 'se-hard-010', topic: 'stellar-evolution', difficulty: 'hard', q: '初始质量函数(IMF)描述的是？', opts: ['恒星形成时不同质量的相对分布', '行星形成函数', '宇宙学距离', '黑洞合并率'], ans: 0, explanation: 'Salpeter IMF 给出 dN/dM ∝ M^-2.35,主导星团整体演化。' },
  { id: 'se-hard-011', topic: 'stellar-evolution', difficulty: 'hard', q: '"太阳中微子问题"最终通过什么解释？', opts: ['探测器误差', '中微子振荡(味道转换)', '太阳模型错误', '中微子衰变'], ans: 1, explanation: '中微子在传播中味道振荡,SNO 实验证实,获得2015诺贝尔物理学奖。' },
  { id: 'se-hard-012', topic: 'stellar-evolution', difficulty: 'hard', q: '红超巨星向沃尔夫-拉叶星演化通常需要？', opts: ['丢失大量外层质量', '增加金属丰度', '降温', '吸积大质量伴星'], ans: 0, explanation: '通过强星风或双星交互剥离氢壳,暴露更深热层成为 WR 星。' },
  { id: 'se-hard-013', topic: 'stellar-evolution', difficulty: 'hard', q: '关于 Ia 型超新星的"双简并"通道是指？', opts: ['白矮星与红巨星合并', '两颗白矮星并合', '中子星与白矮星合并', '黑洞合并'], ans: 1, explanation: '双简并通道:两颗 CO 白矮星并合达到引爆条件;另一类是单简并(白矮星+伴星吸积)。' },
  { id: 'se-hard-014', topic: 'stellar-evolution', difficulty: 'hard', q: '恒星震动学(asteroseismology)主要利用什么数据？', opts: ['色散关系', '光变曲线中的振荡频谱', '质谱', '射电脉冲'], ans: 1, explanation: '通过精密测光提取恒星表面振荡频谱反演内部结构,Kepler/TESS 大量应用。' },
  { id: 'se-hard-015', topic: 'stellar-evolution', difficulty: 'hard', q: '伽马暴(GRB)的长暴普遍认为起源于？', opts: ['白矮星合并', '快速自转大质量恒星核坍缩(collapsar 模型)', '行星撕裂', '宇宙弦'], ans: 1, explanation: '长 GRB 与超新星 Ic 关联,collapsar 模型认为黑洞吸积驱动相对论喷流。' },

  // ============ 星系与宇宙 - 初级 ============
  { id: 'gu-easy-001', topic: 'galaxy-universe', difficulty: 'easy', q: '我们所在的星系叫？', opts: ['仙女座星系', '银河系', '三角座星系', '麦哲伦云'], ans: 1, explanation: '太阳系位于银河系的猎户臂中。' },
  { id: 'gu-easy-002', topic: 'galaxy-universe', difficulty: 'easy', q: '银河系大致是什么形状？', opts: ['椭圆形', '不规则', '棒旋星系', '球状'], ans: 2, explanation: '银河系是带有中央棒结构的旋涡星系。' },
  { id: 'gu-easy-003', topic: 'galaxy-universe', difficulty: 'easy', q: '距离我们最近的大型星系是？', opts: ['仙女座星系', '三角座星系', '南门二星系', '半人马座 A'], ans: 0, explanation: '仙女座星系(M31)距地球约250万光年。' },
  { id: 'gu-easy-004', topic: 'galaxy-universe', difficulty: 'easy', q: '宇宙起源的主流理论是？', opts: ['稳态宇宙', '大爆炸理论', '永恒宇宙', '震荡宇宙'], ans: 1, explanation: '大爆炸理论被宇宙微波背景辐射等观测强力支持。' },
  { id: 'gu-easy-005', topic: 'galaxy-universe', difficulty: 'easy', q: '宇宙的年龄大约是？', opts: ['46亿年', '约138亿年', '5000亿年', '无限'], ans: 1, explanation: '根据普朗克卫星等观测,宇宙年龄约138亿年。' },
  { id: 'gu-easy-006', topic: 'galaxy-universe', difficulty: 'easy', q: '"光年"是什么单位？', opts: ['时间单位', '距离单位(光在一年中走过的距离)', '亮度单位', '能量单位'], ans: 1, explanation: '一光年约9.46万亿公里。' },
  { id: 'gu-easy-007', topic: 'galaxy-universe', difficulty: 'easy', q: '星系按形态可分为？', opts: ['只有一类', '旋涡、椭圆、不规则等', '只有圆形', '只有方形'], ans: 1, explanation: '哈勃星系分类法将星系分为旋涡(S)、棒旋(SB)、椭圆(E)、不规则(Irr)。' },
  { id: 'gu-easy-008', topic: 'galaxy-universe', difficulty: 'easy', q: '银河系中心存在什么样的大质量天体？', opts: ['中子星', '超大质量黑洞', '红巨星', '类星体'], ans: 1, explanation: '人马座 A* 是银河系中心约430万倍太阳质量的超大质量黑洞。' },
  { id: 'gu-easy-009', topic: 'galaxy-universe', difficulty: 'easy', q: '在晴朗夜空中肉眼可见的"银河"实际上是？', opts: ['一条河流', '银河系盘面方向上密集的恒星和星云', '彗星轨迹', '极光'], ans: 1, explanation: '我们看到的"银河"是银盘上无数恒星和气体云的集合视角。' },
  { id: 'gu-easy-010', topic: 'galaxy-universe', difficulty: 'easy', q: '宇宙微波背景辐射(CMB)的温度约为？', opts: ['约2.7K', '300K', '0K', '1000K'], ans: 0, explanation: 'CMB 是宇宙38万年时的"余晖",今天温度约2.725K。' },
  { id: 'gu-easy-011', topic: 'galaxy-universe', difficulty: 'easy', q: '"星座"是？', opts: ['真实物理结构', '人为划分的天区,恒星实际无关', '银河系小区域', '行星集群'], ans: 1, explanation: '同一星座的星可能距离迥异,只是地球视角上的方位组合。' },
  { id: 'gu-easy-012', topic: 'galaxy-universe', difficulty: 'easy', q: '银河系直径大约是？', opts: ['1光年', '10万光年', '100亿光年', '1光分'], ans: 1, explanation: '银河系盘面直径约10万光年。' },
  { id: 'gu-easy-013', topic: 'galaxy-universe', difficulty: 'easy', q: '哈勃定律最初描述的是？', opts: ['行星轨道', '星系退行速度与距离成正比', '黑洞质量', '光年定义'], ans: 1, explanation: '哈勃发现星系普遍远离我们,且距离越远退行越快,提示宇宙膨胀。' },
  { id: 'gu-easy-014', topic: 'galaxy-universe', difficulty: 'easy', q: '银河系有几条主要旋臂(主流模型)？', opts: ['1条', '2条主臂为主,辅以多条次臂', '20条', '没有'], ans: 1, explanation: '近年红外巡天显示英仙臂、人马-半人马臂为两条主旋臂。' },
  { id: 'gu-easy-015', topic: 'galaxy-universe', difficulty: 'easy', q: '"本星系群"中包含哪些主要成员？', opts: ['银河系、仙女座星系、三角座星系等约80个星系', '只有银河系', '银河系和大麦哲伦云', '银河系和仙女座'], ans: 0, explanation: '本星系群直径约1000万光年,以银河系和仙女座星系为两大引力中心。' },

  // ============ 星系与宇宙 - 中级 ============
  { id: 'gu-medium-001', topic: 'galaxy-universe', difficulty: 'medium', q: '"红移"现象通常表明什么？', opts: ['天体在靠近', '天体在远离或宇宙膨胀', '天体在自转', '天体磁化'], ans: 1, explanation: '光谱向长波移动,多普勒红移或宇宙学红移。' },
  { id: 'gu-medium-002', topic: 'galaxy-universe', difficulty: 'medium', q: '哈勃常数 H₀ 的当前测量值大约是？', opts: ['约70 km/s/Mpc', '300000 km/s', '9.8 m/s²', '1光年/年'], ans: 0, explanation: '不同方法给出约 67-73 km/s/Mpc,存在"哈勃张力"。' },
  { id: 'gu-medium-003', topic: 'galaxy-universe', difficulty: 'medium', q: '宇宙学中的暗物质主要通过什么观测推断？', opts: ['直接成像', '星系自转曲线、引力透镜、CMB等', '彩色光谱', '无线电信号'], ans: 1, explanation: '星系外缘转速过快、引力透镜质量过剩,均指向暗物质存在。' },
  { id: 'gu-medium-004', topic: 'galaxy-universe', difficulty: 'medium', q: '暗能量被用来解释什么现象？', opts: ['星系旋转', '宇宙加速膨胀', 'CMB存在', '黑洞蒸发'], ans: 1, explanation: '1998 年Ia 超新星观测显示宇宙在加速膨胀,需引入暗能量。' },
  { id: 'gu-medium-005', topic: 'galaxy-universe', difficulty: 'medium', q: '类星体(quasar)的本质是？', opts: ['超新星', '活跃星系核(AGN)中心吸积大量物质的超大质量黑洞', '脉冲星', '星云'], ans: 1, explanation: '类星体是 AGN 中最明亮一类,光度可超过整个星系。' },
  { id: 'gu-medium-006', topic: 'galaxy-universe', difficulty: 'medium', q: '银河系最近的卫星星系之一是？', opts: ['仙女座', '大麦哲伦云', '室女座星系团', '飞马座'], ans: 1, explanation: '大麦哲伦云距离约16万光年,是显著的不规则卫星星系。' },
  { id: 'gu-medium-007', topic: 'galaxy-universe', difficulty: 'medium', q: '"宇宙暴胀"理论解决了哪些问题？', opts: ['行星运动', '视界问题、平坦性问题、磁单极问题', '黑洞蒸发', '中子星结构'], ans: 1, explanation: '暴胀假设宇宙在极早期指数膨胀,解释了多个观测谜题。' },
  { id: 'gu-medium-008', topic: 'galaxy-universe', difficulty: 'medium', q: '"再电离时代"指的是？', opts: ['宇宙诞生', '宇宙大尺度结构再次被首批恒星类星体电离的时期', '黑洞蒸发', '银河形成'], ans: 1, explanation: '约红移6-15期间,中性氢被首批源辐射再次电离。' },
  { id: 'gu-medium-009', topic: 'galaxy-universe', difficulty: 'medium', q: 'CMB 的发现者是？', opts: ['哈勃', '彭齐亚斯与威尔逊', '爱因斯坦', '霍金'], ans: 1, explanation: '1964年彭齐亚斯与威尔逊偶然发现宇宙微波背景,获1978年诺贝尔奖。' },
  { id: 'gu-medium-010', topic: 'galaxy-universe', difficulty: 'medium', q: '室女座星系团是什么？', opts: ['本星系群一部分', '距离约5400万光年的大型星系团,本超星系团核心', '虚构星座', '行星集合'], ans: 1, explanation: '室女座星系团包含上千成员,是本超星系团的中心。' },
  { id: 'gu-medium-011', topic: 'galaxy-universe', difficulty: 'medium', q: '"标准烛光"在宇宙学测距中常用哪种天体？', opts: ['行星', 'Ia 型超新星与造父变星', '彗星', '黑洞'], ans: 1, explanation: 'Ia 超新星亮度高且较一致,造父变星周光关系经典,共同建立距离阶梯。' },
  { id: 'gu-medium-012', topic: 'galaxy-universe', difficulty: 'medium', q: '银河系大约多久自转一圈(太阳所在位置)？', opts: ['1万年', '约2.3-2.5亿年', '1亿光年', '46亿年'], ans: 1, explanation: '太阳绕银心一周称银河年,约2.25亿地球年。' },
  { id: 'gu-medium-013', topic: 'galaxy-universe', difficulty: 'medium', q: '"星暴星系"通常表现为？', opts: ['静止', '极高的恒星形成率,常因星系并合诱发', '没有恒星', '中央无活动'], ans: 1, explanation: '星暴星系单位时间形成大量恒星,远红外辐射强烈。' },
  { id: 'gu-medium-014', topic: 'galaxy-universe', difficulty: 'medium', q: '哈勃极深场(HUDF)主要展示了？', opts: ['火星地形', '极远距离上数千个早期星系', '太阳光球', '银心'], ans: 1, explanation: 'HUDF 是哈勃望远镜对一小片暗天区超长曝光,展示了宇宙早期星系。' },
  { id: 'gu-medium-015', topic: 'galaxy-universe', difficulty: 'medium', q: 'Ia 型超新星观测在 1998 年带来的重大发现是？', opts: ['黑洞存在', '宇宙加速膨胀(2011年诺贝尔奖)', '太阳寿命', '行星普遍存在'], ans: 1, explanation: 'Perlmutter、Schmidt、Riess 团队由超新星距离-红移得出加速膨胀。' },

  // ============ 星系与宇宙 - 高级 ============
  { id: 'gu-hard-001', topic: 'galaxy-universe', difficulty: 'hard', q: 'ΛCDM 模型中的 Λ 与 CDM 分别代表？', opts: ['暗物质与暗能量', '宇宙学常数(暗能量)与冷暗物质', '辐射与重子', '中微子与黑洞'], ans: 1, explanation: 'ΛCDM 是当前主流宇宙学模型:宇宙学常数+冷暗物质+普通物质。' },
  { id: 'gu-hard-002', topic: 'galaxy-universe', difficulty: 'hard', q: '声学振荡(BAO)在大尺度结构中体现为？', opts: ['星系数量随机', '约150 Mpc 处的相关函数特征尺度', '黑洞分布', '伽马暴聚集'], ans: 1, explanation: 'BAO 来自早期重子-光子流体声波,凝固后留下约150 Mpc 标准尺。' },
  { id: 'gu-hard-003', topic: 'galaxy-universe', difficulty: 'hard', q: '宇宙学红移与多普勒红移本质区别在于？', opts: ['没区别', '宇宙学红移源自空间度规膨胀,光波随空间被拉伸', '都是引力效应', '都是量子效应'], ans: 1, explanation: '宇宙学红移是FRW度规中波长随尺度因子a(t)拉伸的结果。' },
  { id: 'gu-hard-004', topic: 'galaxy-universe', difficulty: 'hard', q: 'CMB 各向异性峰位置主要约束什么？', opts: ['宇宙年龄', '空间曲率与几何', '中子星密度', '太阳活动'], ans: 1, explanation: '第一声学峰角尺度对应平直宇宙几何,Ω_total ≈ 1。' },
  { id: 'gu-hard-005', topic: 'galaxy-universe', difficulty: 'hard', q: '"哈勃张力"指的是？', opts: ['天文望远镜机械问题', 'CMB 推断与近邻测量给出 H₀ 不一致', '宇宙年龄不可知', '银心运动异常'], ans: 1, explanation: 'CMB+ΛCDM 得 H₀≈67,造父+SN Ia 得 ≈73,差异约5σ。' },
  { id: 'gu-hard-006', topic: 'galaxy-universe', difficulty: 'hard', q: '"末态宇宙"模型 "Big Rip" 假设？', opts: ['宇宙塌缩', '暗能量状态参数 w<-1 致使一切结构被撕裂', '黑洞合并', '宇宙稳态'], ans: 1, explanation: 'phantom 暗能量(w<-1)会使尺度因子有限时间内发散,撕裂结构。' },
  { id: 'gu-hard-007', topic: 'galaxy-universe', difficulty: 'hard', q: '"星系演化"中,主序图(SFR-M*)的"主序"是指？', opts: ['赫罗主序', '恒星形成星系在恒星形成率与质量关系上的窄带', '星系亮度等级', 'CMB 平均'], ans: 1, explanation: '近主序的星系SFR与M*近似幂律关系,偏离区为静止/星暴星系。' },
  { id: 'gu-hard-008', topic: 'galaxy-universe', difficulty: 'hard', q: 'M-σ 关系联系的是？', opts: ['行星质量与轨道', '超大质量黑洞质量与寄主星系核球速度弥散', 'CMB 涨落', '中子星脉动'], ans: 1, explanation: 'M-σ 关系暗示黑洞与星系核球协同演化,反馈机制重要。' },
  { id: 'gu-hard-009', topic: 'galaxy-universe', difficulty: 'hard', q: '"莱曼-α 森林"指的是？', opts: ['森林星座', '类星体光谱中由不同红移氢云造成的吸收线序列', '射电图样', '银晕结构'], ans: 1, explanation: '中性氢沿视线吸收Lyα,造成密集吸收线,可探测星系际介质结构。' },
  { id: 'gu-hard-010', topic: 'galaxy-universe', difficulty: 'hard', q: '宇宙暴胀产生的"标量谱指数 nₛ"目前测量值约为？', opts: ['1.0', '约0.965,略小于1', '0.5', '2.0'], ans: 1, explanation: '普朗克测量 nₛ≈0.965,支持稍微"红倾斜"的暴胀谱。' },
  { id: 'gu-hard-011', topic: 'galaxy-universe', difficulty: 'hard', q: '关于暗物质性质,以下哪类候选已被 LUX-ZEPLIN/PandaX 等大幅排除参数空间？', opts: ['MACHOs', 'WIMPs(弱相互作用大质量粒子)在百GeV尺度', '引力波', '引力子'], ans: 1, explanation: '直接探测实验持续压缩 WIMP-核子散射截面参数空间,但仍未排除全部模型。' },
  { id: 'gu-hard-012', topic: 'galaxy-universe', difficulty: 'hard', q: '本星系群中,银河系与仙女座星系预计将于何时发生主要并合？', opts: ['10亿年内', '约45亿年后', '永不发生', '已发生'], ans: 1, explanation: '基于 Gaia 测量切向速度,M31 与银河系将在约45亿年后并合形成"Milkomeda"。' },
  { id: 'gu-hard-013', topic: 'galaxy-universe', difficulty: 'hard', q: 'Sachs-Wolfe 效应描述的是？', opts: ['行星运动', 'CMB 光子穿越引力势阱产生的温度涨落', '引力波', '中微子振荡'], ans: 1, explanation: 'CMB 光子翻越大尺度势阱发生频移,贡献低多极矩涨落。' },
  { id: 'gu-hard-014', topic: 'galaxy-universe', difficulty: 'hard', q: '原初引力波若被探测到,主要用以约束？', opts: ['行星形成', '暴胀能量尺度与张量-标量比 r', '黑洞蒸发', '太阳模型'], ans: 1, explanation: 'CMB 的 B 模偏振若来自原初引力波,可直接约束暴胀能标。' },
  { id: 'gu-hard-015', topic: 'galaxy-universe', difficulty: 'hard', q: '"21cm 信号"在宇宙学中的科学意义是？', opts: ['探测中性氢演化、再电离与黑暗时代', '研究太阳活动', '探测系外行星', '研究火星水冰'], ans: 0, explanation: '21cm 中性氢超精细跃迁可追踪从黑暗时代到再电离的宇宙演化。' },

  // ============ 航天探索史 - 初级 ============
  { id: 'sp-easy-001', topic: 'space-exploration', difficulty: 'easy', q: '人类发射的第一颗人造卫星是？', opts: ['探险者1号', '斯普特尼克1号', '东方红1号', '阿波罗1号'], ans: 1, explanation: '苏联1957年10月4日发射斯普特尼克1号,开启太空时代。' },
  { id: 'sp-easy-002', topic: 'space-exploration', difficulty: 'easy', q: '世界上第一位进入太空的宇航员是？', opts: ['尼尔·阿姆斯特朗', '尤里·加加林', '杨利伟', '约翰·格伦'], ans: 1, explanation: '加加林1961年4月12日乘东方1号成为太空第一人。' },
  { id: 'sp-easy-003', topic: 'space-exploration', difficulty: 'easy', q: '人类首次登月是哪个任务？', opts: ['阿波罗11号', '阿波罗13号', '阿波罗1号', '双子星座7号'], ans: 0, explanation: '阿波罗11号于1969年7月20日成功登月。' },
  { id: 'sp-easy-004', topic: 'space-exploration', difficulty: 'easy', q: '中国第一颗人造卫星是？', opts: ['东方红1号', '神舟1号', '嫦娥1号', '风云1号'], ans: 0, explanation: '1970年4月24日发射的东方红1号,使中国成为第五个独立发射卫星的国家。' },
  { id: 'sp-easy-005', topic: 'space-exploration', difficulty: 'easy', q: '中国首位进入太空的航天员是？', opts: ['杨利伟', '费俊龙', '刘伯明', '景海鹏'], ans: 0, explanation: '2003年10月15日杨利伟乘神舟5号执行任务。' },
  { id: 'sp-easy-006', topic: 'space-exploration', difficulty: 'easy', q: '国际空间站(ISS)是哪些国家共同合作建造的？', opts: ['仅美国', '美俄欧加日五方主导多国合作', '中国独立', '只有欧盟'], ans: 1, explanation: '15国合作的多舱段空间站,1998年开始组装。' },
  { id: 'sp-easy-007', topic: 'space-exploration', difficulty: 'easy', q: '"嫦娥工程"是中国哪一类探测任务？', opts: ['火星探测', '月球探测', '太阳探测', '小行星采样'], ans: 1, explanation: '嫦娥工程系列围绕月球的绕、落、回三步走计划。' },
  { id: 'sp-easy-008', topic: 'space-exploration', difficulty: 'easy', q: '人类首次月球背面软着陆是哪艘探测器？', opts: ['嫦娥四号', '阿波罗15号', '月神1号', '月球9号'], ans: 0, explanation: '2019年1月3日,嫦娥四号在月球背面冯·卡门撞击坑成功着陆。' },
  { id: 'sp-easy-009', topic: 'space-exploration', difficulty: 'easy', q: '美国"航天飞机"项目共有几架曾运营的轨道器？', opts: ['2', '5', '10', '1'], ans: 1, explanation: '哥伦比亚、挑战者、发现、亚特兰蒂斯、奋进号共5架。' },
  { id: 'sp-easy-010', topic: 'space-exploration', difficulty: 'easy', q: '中国空间站的中文名是？', opts: ['天宫', '神舟', '嫦娥', '北斗'], ans: 0, explanation: '中国空间站命名为"天宫",2022年完成 T 字基本构型。' },
  { id: 'sp-easy-011', topic: 'space-exploration', difficulty: 'easy', q: '人类首次火星表面软着陆是？', opts: ['美国海盗1号(1976)', '中国天问一号', '阿波罗15号', '苏联月球2号'], ans: 0, explanation: '苏联火星3号短暂登陆失败,真正成功长期工作的是NASA海盗1/2号。' },
  { id: 'sp-easy-012', topic: 'space-exploration', difficulty: 'easy', q: '中国首次火星探测任务的名称是？', opts: ['天问一号', '嫦娥三号', '神舟九号', '风云三号'], ans: 0, explanation: '天问一号2020年发射,2021年5月成功着陆,祝融号火星车开展工作。' },
  { id: 'sp-easy-013', topic: 'space-exploration', difficulty: 'easy', q: '哈勃空间望远镜发射于哪一年？', opts: ['1990', '2003', '1969', '2010'], ans: 0, explanation: '哈勃望远镜由发现号航天飞机于1990年4月送入轨道。' },
  { id: 'sp-easy-014', topic: 'space-exploration', difficulty: 'easy', q: '詹姆斯·韦伯空间望远镜的主要观测波段是？', opts: ['可见光', '红外', '射电', 'X射线'], ans: 1, explanation: 'JWST 主要在近红外到中红外波段,有助于观测早期宇宙与冷天体。' },
  { id: 'sp-easy-015', topic: 'space-exploration', difficulty: 'easy', q: 'SpaceX 的可回收火箭代表型号是？', opts: ['猎鹰9号', '土星5号', 'N1', '能源号'], ans: 0, explanation: '猎鹰9号实现了一级火箭的多次回收复用。' },

  // ============ 航天探索史 - 中级 ============
  { id: 'sp-medium-001', topic: 'space-exploration', difficulty: 'medium', q: '"双子星座计划(Gemini)"主要解决什么问题？', opts: ['登月本身', '为登月做铺垫的太空对接、长时间停留与出舱活动技术', '航天飞机研发', '空间站维护'], ans: 1, explanation: '双子星座为阿波罗登月验证了关键的轨道操控技术。' },
  { id: 'sp-medium-002', topic: 'space-exploration', difficulty: 'medium', q: '苏联第一个空间站是？', opts: ['和平号', '礼炮1号', '天宫一号', '天空实验室'], ans: 1, explanation: '礼炮1号于1971年发射,是人类第一个空间站。' },
  { id: 'sp-medium-003', topic: 'space-exploration', difficulty: 'medium', q: '"旅行者1号"目前的状态是？', opts: ['已坠毁', '已飞出日球层顶进入星际空间', '位于火星轨道', '位于木星附近'], ans: 1, explanation: '旅行者1号于2012年成为首个进入星际空间的人造物体。' },
  { id: 'sp-medium-004', topic: 'space-exploration', difficulty: 'medium', q: '"卡西尼-惠更斯"任务的主要目标是？', opts: ['火星', '土星与土卫六', '木星', '冥王星'], ans: 1, explanation: '卡西尼绕土星观测多年,惠更斯探测器登陆土卫六。' },
  { id: 'sp-medium-005', topic: 'space-exploration', difficulty: 'medium', q: '"新视野号(New Horizons)"主要探测了？', opts: ['金星', '冥王星与柯伊伯带天体', '土星', '小行星'], ans: 1, explanation: '2015年飞掠冥王星,后探测柯伊伯带天体 Arrokoth。' },
  { id: 'sp-medium-006', topic: 'space-exploration', difficulty: 'medium', q: '"OSIRIS-REx"任务的目标是？', opts: ['火星采样', '小行星贝努(Bennu)采样返回', '冥王星', '木卫二'], ans: 1, explanation: 'OSIRIS-REx 2020年从贝努采样,2023年样品返回地球。' },
  { id: 'sp-medium-007', topic: 'space-exploration', difficulty: 'medium', q: '"嫦娥五号"实现了什么里程碑？', opts: ['月球背面着陆', '中国首次地外天体采样返回(月壤)', '火星采样', '小行星采样'], ans: 1, explanation: '2020年12月嫦娥五号带回约1731克月壤样本。' },
  { id: 'sp-medium-008', topic: 'space-exploration', difficulty: 'medium', q: '"哈勃望远镜"被多次维修的原因之一是？', opts: ['初期主镜面磨制误差导致成像模糊', '未发射成功', '从未维修', '镜头掉落'], ans: 0, explanation: '1993年第一次维修加装 COSTAR 矫正光学,大幅改善成像。' },
  { id: 'sp-medium-009', topic: 'space-exploration', difficulty: 'medium', q: '"和平号空间站"运行时长约为？', opts: ['1年', '约15年(1986-2001)', '50年', '从未运行'], ans: 1, explanation: '和平号(Mir)运行15年后于2001年受控再入大气层。' },
  { id: 'sp-medium-010', topic: 'space-exploration', difficulty: 'medium', q: '"伽利略号"探测器的主要研究目标是？', opts: ['土星', '木星及其卫星', '金星', '火星'], ans: 1, explanation: '伽利略号 1995-2003 年绕木星运行,详细探测木星系。' },
  { id: 'sp-medium-011', topic: 'space-exploration', difficulty: 'medium', q: '苏联月球计划中首次软着陆并传回月面照片的探测器是？', opts: ['月球9号', '月球17号', '月球1号', '联盟1号'], ans: 0, explanation: '1966年月球9号首次实现月面软着陆并传回图像。' },
  { id: 'sp-medium-012', topic: 'space-exploration', difficulty: 'medium', q: '中国"长征五号"火箭属于哪类运载能力？', opts: ['小型', '大推力大型液体火箭(近地轨道≥25吨)', '亚轨道', '探空火箭'], ans: 1, explanation: '长征五号是中国新一代大型运载火箭,支撑空间站、深空探测。' },
  { id: 'sp-medium-013', topic: 'space-exploration', difficulty: 'medium', q: '"挑战者号"航天飞机失事原因是？', opts: ['轮胎爆裂', 'O 形密封圈低温失效引发右侧助推器结构失效', '燃料用尽', '陨石撞击'], ans: 1, explanation: '1986年挑战者号在升空73秒后解体,导致7名航天员遇难。' },
  { id: 'sp-medium-014', topic: 'space-exploration', difficulty: 'medium', q: 'NASA 的"阿尔忒弥斯计划"目标是？', opts: ['退役 ISS', '让人类重返月球并建立持续存在', '火星采样', '探索木卫二'], ans: 1, explanation: '阿尔忒弥斯旨在使首位女性和有色人种宇航员登月,并建立月轨/月面持续基础设施。' },
  { id: 'sp-medium-015', topic: 'space-exploration', difficulty: 'medium', q: '韦伯望远镜部署于哪个轨道点？', opts: ['近地轨道', '日地拉格朗日点 L2', '月球轨道', '太阳-火星 L1'], ans: 1, explanation: 'JWST 位于约150万公里外的日地 L2,有利低温稳定观测。' },

  // ============ 航天探索史 - 高级 ============
  { id: 'sp-hard-001', topic: 'space-exploration', difficulty: 'hard', q: '苏联 N1 火箭的命运是？', opts: ['成功登月', '4次发射全部失败,登月计划终止', '从未发射', '现役运行'], ans: 1, explanation: '苏联超重型 N1 因发动机集成问题4次发射均失败,登月计划被搁置。' },
  { id: 'sp-hard-002', topic: 'space-exploration', difficulty: 'hard', q: '"先驱者10/11号"的"金属牌匾"内容主要是？', opts: ['人类语言', '人类形象与太阳系位置等基本信息', '银行密码', '随机数据'], ans: 1, explanation: '由 Carl Sagan 等设计,金属牌带有给可能外星接收者的人类信息。' },
  { id: 'sp-hard-003', topic: 'space-exploration', difficulty: 'hard', q: '"罗塞塔号"任务的成就是？', opts: ['火星采样', '伴飞67P/丘留莫夫-格拉西缅科彗星并释放着陆器菲莱', '木星探测', '土卫六登陆'], ans: 1, explanation: '2014年菲莱着陆器历史性地首次降落于一颗彗星。' },
  { id: 'sp-hard-004', topic: 'space-exploration', difficulty: 'hard', q: '"DART"任务于2022年完成了什么科学验证？', opts: ['登陆火星', '撞击小行星 Dimorphos 改变其轨道,验证行星防御', '采样返回', '小行星观测'], ans: 1, explanation: 'DART 撞击改变了 Dimorphos 周期,首次实证动能撞击防御技术。' },
  { id: 'sp-hard-005', topic: 'space-exploration', difficulty: 'hard', q: '欧空局"赫歇尔空间天文台"主要观测波段是？', opts: ['可见光', '远红外/亚毫米', '伽马', '紫外'], ans: 1, explanation: '赫歇尔(2009-2013)用于远红外/亚毫米波段研究恒星形成与星际介质。' },
  { id: 'sp-hard-006', topic: 'space-exploration', difficulty: 'hard', q: '中国天问一号包括哪几个系统组合工作？', opts: ['只有轨道器', '环绕器、着陆器与火星车一次任务完成"绕、着、巡"', '只有火星车', '采样器'], ans: 1, explanation: '一次任务实现绕火、着陆与巡视三大目标,世界航天首次。' },
  { id: 'sp-hard-007', topic: 'space-exploration', difficulty: 'hard', q: '"阿波罗-联盟测试计划"(ASTP)在 1975 年实现了什么？', opts: ['首次月面对接', '美苏飞船首次在轨对接,冷战期间合作的标志', '航天飞机首飞', '空间站启用'], ans: 1, explanation: 'ASTP 是美苏太空合作的破冰之举,为后续合作奠定基础。' },
  { id: 'sp-hard-008', topic: 'space-exploration', difficulty: 'hard', q: 'SpaceX "星舰(Starship)"采用什么推进剂组合？', opts: ['液氢/液氧', '液态甲烷/液氧', '煤油/液氧', '固体燃料'], ans: 1, explanation: '甲烷-氧组合可在火星就地资源生产,适合可重复使用与登陆深空。' },
  { id: 'sp-hard-009', topic: 'space-exploration', difficulty: 'hard', q: 'NASA "帕克太阳探测器(Parker Solar Probe)"近日点距离创下新纪录,大约多近？', opts: ['1 AU', '<10太阳半径(约600万公里)', '0.5 AU', '0.9 AU'], ans: 1, explanation: '帕克探测器多次近日点逐步逼近,最终接近10太阳半径,前所未有。' },
  { id: 'sp-hard-010', topic: 'space-exploration', difficulty: 'hard', q: '"嫦娥工程"的"绕、落、回"分别由哪几号实现？', opts: ['嫦娥1/3/5号', '嫦娥2/4/6号', '嫦娥1/2/3号', '嫦娥3/4/5号'], ans: 0, explanation: '嫦娥一号绕月、嫦娥三号落月、嫦娥五号采样返回,三步走完成。' },
  { id: 'sp-hard-011', topic: 'space-exploration', difficulty: 'hard', q: '"哥伦比亚号"航天飞机失事原因是？', opts: ['发射台爆炸', '隔热瓦受损,再入时高温烧穿导致解体', '主发动机故障', '电池起火'], ans: 1, explanation: '2003年哥伦比亚号再入解体,7名航天员遇难,后航天飞机增加在轨检查程序。' },
  { id: 'sp-hard-012', topic: 'space-exploration', difficulty: 'hard', q: 'JAXA "隼鸟2号(Hayabusa2)"任务带回了什么？', opts: ['月球岩石', '近地小行星龙宫(Ryugu)样本', '彗星气体', '火星土壤'], ans: 1, explanation: '2020年隼鸟2号送回约5.4克龙宫样品,含丰富有机物分析价值。' },
  { id: 'sp-hard-013', topic: 'space-exploration', difficulty: 'hard', q: '"日地空间天气"观测的关键卫星之一 SOHO 由谁运营？', opts: ['NASA 独立', 'NASA 与 ESA 合作', 'JAXA', '中国国家航天局'], ans: 1, explanation: 'SOHO 自1995年起运行,是 NASA-ESA 合作的太阳监测旗舰。' },
  { id: 'sp-hard-014', topic: 'space-exploration', difficulty: 'hard', q: '"玛尔斯快车(Mars Express)"主要由哪国/机构发射并运营？', opts: ['美国NASA', '欧空局ESA', '俄罗斯', '中国'], ans: 1, explanation: 'Mars Express 是 ESA 2003年发射的火星轨道器,持续观测火星至今。' },
  { id: 'sp-hard-015', topic: 'space-exploration', difficulty: 'hard', q: 'NASA"双子星座计划"中首次成功太空行走的宇航员是？', opts: ['爱德华·怀特(Ed White)', '阿姆斯特朗', '阿尔德林', '约翰·格伦'], ans: 0, explanation: '1965年双子星座4号任务中爱德华·怀特完成美国首次太空行走。' },

  // ============ 天文观测 - 初级 ============
  { id: 'ao-easy-001', topic: 'astronomical-observation', difficulty: 'easy', q: '望远镜的两大主要类型是？', opts: ['折射望远镜与反射望远镜', '红外与紫外', '太阳与月球', '光学与机械'], ans: 0, explanation: '折射使用透镜,反射使用反射镜,后者更易做大口径。' },
  { id: 'ao-easy-002', topic: 'astronomical-observation', difficulty: 'easy', q: '观星时"光污染"会造成什么影响？', opts: ['没有影响', '使天空背景变亮、暗弱天体被淹没', '让星星变多', '让月亮发光'], ans: 1, explanation: '城市光散射使夜空变亮,大幅降低天体观测对比度。' },
  { id: 'ao-easy-003', topic: 'astronomical-observation', difficulty: 'easy', q: '北半球夏季银河最亮的方向是？', opts: ['北极星附近', '人马座方向(银河系中心)', '猎户座', '狮子座'], ans: 1, explanation: '银心位于人马座方向,夏夜银河最浓密。' },
  { id: 'ao-easy-004', topic: 'astronomical-observation', difficulty: 'easy', q: '使用双筒望远镜观月时最佳时段是？', opts: ['满月', '新月', '上弦或下弦,陨石坑阴影最明显', '日食'], ans: 2, explanation: '弦月时晨昏线附近的陨石坑因阴影立体感最强。' },
  { id: 'ao-easy-005', topic: 'astronomical-observation', difficulty: 'easy', q: '"流星雨"通常源于？', opts: ['行星碰撞', '地球穿越彗星或小行星残留尘埃带', '太阳风暴', '黑洞辐射'], ans: 1, explanation: '比如英仙座流星雨源自斯威夫特-塔特尔彗星尘埃。' },
  { id: 'ao-easy-006', topic: 'astronomical-observation', difficulty: 'easy', q: '一个常见的天文现象——"黄道光"出现在？', opts: ['日落后的西方或日出前的东方', '正午', '深夜中天', '月食时'], ans: 0, explanation: '黄道光来源于行星际尘埃对太阳光的散射,沿黄道呈锥形微光。' },
  { id: 'ao-easy-007', topic: 'astronomical-observation', difficulty: 'easy', q: '"日食"发生时,日地月的位置是？', opts: ['月-地-日', '日-月-地(月球位于地球与太阳之间)', '日-地-月', '随机'], ans: 1, explanation: '月球遮住太阳产生日食。' },
  { id: 'ao-easy-008', topic: 'astronomical-observation', difficulty: 'easy', q: '"月食"发生时月相是？', opts: ['新月', '满月', '上弦', '下弦'], ans: 1, explanation: '月食只在月球进入地球本影,即满月时可能发生。' },
  { id: 'ao-easy-009', topic: 'astronomical-observation', difficulty: 'easy', q: '"星等"最早由谁提出？', opts: ['哈勃', '希帕克斯', '伽利略', '爱因斯坦'], ans: 1, explanation: '希帕克斯将肉眼可见星按亮度分1-6等。' },
  { id: 'ao-easy-010', topic: 'astronomical-observation', difficulty: 'easy', q: '夜空中肉眼可分辨大约多少颗星？', opts: ['约1000颗', '极佳条件下约6000颗(全天)', '只有几十颗', '上亿颗'], ans: 1, explanation: '极暗夜空全天约6000颗肉眼可见星(实际任意时刻只能看到一半)。' },
  { id: 'ao-easy-011', topic: 'astronomical-observation', difficulty: 'easy', q: '北极星可以指示哪个方向(北半球观察)？', opts: ['正北', '正南', '正东', '正西'], ans: 0, explanation: '北极星几乎位于地球自转轴北延长线,夜间指北。' },
  { id: 'ao-easy-012', topic: 'astronomical-observation', difficulty: 'easy', q: '"日珥"是从太阳何处喷出？', opts: ['核心', '色球层与日冕中', '太阳系外', '光球深处'], ans: 1, explanation: '日珥是色球向日冕延伸的等离子体环,与磁场密切相关。' },
  { id: 'ao-easy-013', topic: 'astronomical-observation', difficulty: 'easy', q: '"梅西耶天体"系列(M1-M110)主要包括？', opts: ['行星', '彗星', '深空天体如星云、星团、星系', '小行星'], ans: 2, explanation: '梅西耶最初编制是为避免与彗星混淆,意外成为深空观测经典清单。' },
  { id: 'ao-easy-014', topic: 'astronomical-observation', difficulty: 'easy', q: '"赤纬"在天文坐标中相当于地理上的什么？', opts: ['经度', '纬度', '高度', '时间'], ans: 1, explanation: '赤纬类似纬度,赤经类似经度,合称赤道坐标系。' },
  { id: 'ao-easy-015', topic: 'astronomical-observation', difficulty: 'easy', q: '观察日食必须使用？', opts: ['普通太阳镜', '专业巴德膜或日食专用滤光设备', '相机镜头', '不用任何防护'], ans: 1, explanation: '直视太阳极危险,必须用合规减光>10万倍的滤光膜或望远镜专用滤光器。' },

  // ============ 天文观测 - 中级 ============
  { id: 'ao-medium-001', topic: 'astronomical-observation', difficulty: 'medium', q: '"分辨率"在望远镜中近似遵循 1.22λ/D,这表明？', opts: ['口径越小越清晰', '更大口径与更短波长有更好的角分辨率', '与口径无关', '只取决于天气'], ans: 1, explanation: '艾里斑直径 ~1.22λ/D,大口径短波长更优。' },
  { id: 'ao-medium-002', topic: 'astronomical-observation', difficulty: 'medium', q: '"自适应光学"(AO)的主要作用是？', opts: ['增加曝光', '实时校正大气湍流以恢复衍射极限', '冷却 CCD', '提高放大倍率'], ans: 1, explanation: 'AO 用变形镜根据导星波前实时矫正,显著提升地面望远镜分辨率。' },
  { id: 'ao-medium-003', topic: 'astronomical-observation', difficulty: 'medium', q: '射电望远镜阵列采用"干涉合成孔径"技术目的是？', opts: ['增加灵敏度', '通过基线扩大等效口径,获得高分辨率', '降低噪声', '加快对焦'], ans: 1, explanation: 'VLA、ALMA、EHT 等通过干涉合成等效大口径,实现高角分辨率。' },
  { id: 'ao-medium-004', topic: 'astronomical-observation', difficulty: 'medium', q: '"事件视界望远镜(EHT)"于 2019 年发布的成果是？', opts: ['火星照片', 'M87 中心黑洞首张直接图像', '冥王星彩色照片', '木卫二地形图'], ans: 1, explanation: 'EHT 通过 VLBI 在毫米波段成像 M87* 黑洞阴影,2022年又发布Sgr A*。' },
  { id: 'ao-medium-005', topic: 'astronomical-observation', difficulty: 'medium', q: '中国 FAST 望远镜是？', opts: ['空间望远镜', '500米口径球面射电望远镜', '光学望远镜', '紫外望远镜'], ans: 1, explanation: 'FAST 位于贵州,主接收面500米,是单口径射电望远镜世界第一。' },
  { id: 'ao-medium-006', topic: 'astronomical-observation', difficulty: 'medium', q: '"光谱分析"在天文观测中能直接告诉我们？', opts: ['天体的磁场强度仅', '化学成分、温度、运动速度等', '天体形状', '观察者意图'], ans: 1, explanation: '光谱线身份显示成分,位移给出速度,展宽提示热运动等信息。' },
  { id: 'ao-medium-007', topic: 'astronomical-observation', difficulty: 'medium', q: '"测光"与"光谱"观测的差别在于？', opts: ['没有差别', '测光只测光强随时间/波段;光谱细致分解波长', '测光更精细', '光谱只是大致估算'], ans: 1, explanation: '测光得到光变曲线,光谱得到波长能量分布,各有侧重。' },
  { id: 'ao-medium-008', topic: 'astronomical-observation', difficulty: 'medium', q: '"光行差"现象由谁首次解释？', opts: ['哈雷', '布拉德利(James Bradley)', '哥白尼', '伽利略'], ans: 1, explanation: '1727年布拉德利由观测推断光行差,提供地球运动证据。' },
  { id: 'ao-medium-009', topic: 'astronomical-observation', difficulty: 'medium', q: 'CCD 相比胶片的主要优势是？', opts: ['更便宜', '量子效率高、线性响应、可数字处理', '颜色更艳', '不需要电源'], ans: 1, explanation: 'CCD/CMOS 量子效率可达90%以上,远胜胶片几个百分点。' },
  { id: 'ao-medium-010', topic: 'astronomical-observation', difficulty: 'medium', q: '"北天极"附近变化最大的因素之一是？', opts: ['银盘旋转', '岁差导致地轴25800年周期摆动', '日食频率', '大气湍流'], ans: 1, explanation: '岁差使北极星身份会随时间变化,如未来北极星将是织女星。' },
  { id: 'ao-medium-011', topic: 'astronomical-observation', difficulty: 'medium', q: '"远紫外"与"X 射线"观测一般需要在哪里进行？', opts: ['地面任意位置', '大气层之外(空间望远镜)', '海底', '高山顶可完全代替'], ans: 1, explanation: '大气吸收 UV 与 X 射线,需要空间望远镜如 Chandra、XMM-Newton。' },
  { id: 'ao-medium-012', topic: 'astronomical-observation', difficulty: 'medium', q: '在天文学中,"视星等"与"绝对星等"差别为？', opts: ['视星等是观测亮度;绝对星等是10秒差距处的标准化亮度', '完全相同', '绝对星等只用于太阳', '没区别'], ans: 0, explanation: '绝对星等消除距离影响,反映天体真实亮度。' },
  { id: 'ao-medium-013', topic: 'astronomical-observation', difficulty: 'medium', q: '"视差测距"主要用于？', opts: ['银河系外星系', '银河系内近距离恒星', '星系团', 'CMB'], ans: 1, explanation: '地球轨道半径作为基线,几何测距,Gaia 已扩展到数千秒差距。' },
  { id: 'ao-medium-014', topic: 'astronomical-observation', difficulty: 'medium', q: '"凌日法"探测系外行星的原理是？', opts: ['监测行星反射光', '观测行星经过恒星前方导致的光度微小下降', '直接成像', '射电信号'], ans: 1, explanation: 'Kepler/TESS 等利用凌日法发现大量系外行星。' },
  { id: 'ao-medium-015', topic: 'astronomical-observation', difficulty: 'medium', q: '"光速漂移"(secular drift)如赤经变化对长期目标的影响主要由？', opts: ['岁差与章动', '银河系自转', '行星扰动', '大气折射'], ans: 0, explanation: '岁差(>2万年)与章动(18.6年)导致天球坐标系长期与短期摆动。' },

  // ============ 天文观测 - 高级 ============
  { id: 'ao-hard-001', topic: 'astronomical-observation', difficulty: 'hard', q: '甚长基线干涉(VLBI)能够取得极高分辨率,主要因为？', opts: ['CCD 灵敏', '基线可达地球直径量级,等效口径极大', '使用激光', '低温环境'], ans: 1, explanation: 'EHT 利用全球分布站点形成洲际基线,角分辨率达到微角秒。' },
  { id: 'ao-hard-002', topic: 'astronomical-observation', difficulty: 'hard', q: '韦伯望远镜的主镜采用什么材料?为什么？', opts: ['普通玻璃,便宜', '镀金铍质蜂窝结构,质量轻、热稳定、对红外反射率高', '铜', '塑料'], ans: 1, explanation: '铍轻且低热膨胀,镀金对红外反射率>98%,适合冷态深空观测。' },
  { id: 'ao-hard-003', topic: 'astronomical-observation', difficulty: 'hard', q: 'LIGO/Virgo 探测引力波的工作原理是？', opts: ['雷达', '迈克尔逊-莫雷干涉测量两臂长度差小至10⁻¹⁹米', '电场', '射电'], ans: 1, explanation: '引力波拉伸/压缩干涉臂长,极精密干涉测量探测到 GW150914 等事件。' },
  { id: 'ao-hard-004', topic: 'astronomical-observation', difficulty: 'hard', q: '"自适应光学"中常用"激光导星"的目的是？', opts: ['美观', '在缺乏自然亮星时人工激发钠层荧光作为参考波前', '加热目标', '指示方位'], ans: 1, explanation: '钠层激光导星可用于绝大多数天区测量大气波前。' },
  { id: 'ao-hard-005', topic: 'astronomical-observation', difficulty: 'hard', q: '"日震学/星震学"中,使用频谱反演恒星内部结构的依据是？', opts: ['光强与温度', '声学/重力模式频率对内部物理结构敏感', '颜色变化', '磁场'], ans: 1, explanation: '不同模式探测不同深度,精确测量频率反演内部声速、转动等。' },
  { id: 'ao-hard-006', topic: 'astronomical-observation', difficulty: 'hard', q: '"中微子天文学"探测器多置于深地或深海/冰下的原因是？', opts: ['美观', '屏蔽宇宙线背景以识别极弱的中微子事件', '降温', '测试材料'], ans: 1, explanation: '深处屏蔽μ子等背景,如 IceCube 在南极冰层中。' },
  { id: 'ao-hard-007', topic: 'astronomical-observation', difficulty: 'hard', q: '"多信使天文学"指的是？', opts: ['多个望远镜', '联合电磁波、引力波、中微子、宇宙线等不同载体观测', '不同语言报告', '多种媒体宣传'], ans: 1, explanation: 'GW170817 双中子星合并事件首次实现引力波+电磁波多信使观测。' },
  { id: 'ao-hard-008', topic: 'astronomical-observation', difficulty: 'hard', q: '"光子计数 EMCCD"相对常规 CCD 的优势是？', opts: ['更便宜', '电子倍增显著降低读出噪声,适合极暗弱光信号高速成像', '无暗电流', '不需要冷却'], ans: 1, explanation: 'EMCCD 在低光时几乎可计数光子,适合自适应光学等高频应用。' },
  { id: 'ao-hard-009', topic: 'astronomical-observation', difficulty: 'hard', q: '"占星学"与"天文学"的关系是？', opts: ['同一学科', '两者已分离,占星学非现代科学;天文学是基于物理的科学', '占星学更精确', '没区别'], ans: 1, explanation: '科学界明确区分:天文学是自然科学,占星学没有可重复的科学证据。' },
  { id: 'ao-hard-010', topic: 'astronomical-observation', difficulty: 'hard', q: '"重力透镜"被用于研究什么？', opts: ['行星轨道', '星系/星系团质量分布、暗物质、远距离星系成像', '太阳活动', '行星大气'], ans: 1, explanation: '强透镜成像与弱透镜统计是测量暗物质分布的主要工具。' },
  { id: 'ao-hard-011', topic: 'astronomical-observation', difficulty: 'hard', q: '"角秒(arcsec)"在地面光学观测中,典型大气视宁度约为？', opts: ['1毫角秒', '约1角秒(优良台址0.5-1.5″)', '60角秒', '180°'], ans: 1, explanation: '冒纳凯阿、ELT 候选地等优秀地点可达0.5-0.8角秒甚至更佳。' },
  { id: 'ao-hard-012', topic: 'astronomical-observation', difficulty: 'hard', q: 'Gaia 卫星主要任务是？', opts: ['大气观测', '高精度测量银河系约20亿恒星的位置、距离与运动', '探测火星', '研究太阳'], ans: 1, explanation: 'Gaia 通过精密测光与天体测量绘制银河系三维高精度地图。' },
  { id: 'ao-hard-013', topic: 'astronomical-observation', difficulty: 'hard', q: '"切伦科夫望远镜"探测什么？', opts: ['可见光直接成像', '高能宇宙伽马射线在大气中产生的切伦科夫光', '射电', '红外'], ans: 1, explanation: '高能γ光子撞击大气产生粒子簇射,引发蓝光,被地面阵列探测。' },
  { id: 'ao-hard-014', topic: 'astronomical-observation', difficulty: 'hard', q: '"阿塔卡马大型毫米/亚毫米阵列(ALMA)"主要观测什么？', opts: ['可见光', '冷尘埃、原行星盘、分子谱线等的毫米/亚毫米发射', '伽马', '紫外'], ans: 1, explanation: 'ALMA 在低温干燥的智利高原,可清晰成像原行星盘等冷天体。' },
  { id: 'ao-hard-015', topic: 'astronomical-observation', difficulty: 'hard', q: '"恒星视向速度"在系外行星探测中能告诉我们？', opts: ['行星颜色', '通过多普勒摆动反演行星最低质量与轨道', '行星表面温度', '直接成像分辨率'], ans: 1, explanation: '径向速度法配合凌日可解出绝对质量、密度等关键参数。' },

  // ============ 宇宙物理 - 初级 ============
  { id: 'ap-easy-001', topic: 'astrophysics', difficulty: 'easy', q: '光速在真空中约为？', opts: ['30万 km/s', '3000 km/s', '300 km/s', '300000 km/h'], ans: 0, explanation: '真空光速 c ≈ 299792458 m/s ≈ 30万 km/s。' },
  { id: 'ap-easy-002', topic: 'astrophysics', difficulty: 'easy', q: '宇宙中已知最快传播的是？', opts: ['声波', '电磁波(光)', '引力波也以光速传播', 'B和C都对'], ans: 3, explanation: '光与引力波在真空中均以光速传播,这是上限。' },
  { id: 'ap-easy-003', topic: 'astrophysics', difficulty: 'easy', q: '黑洞的"事件视界"是什么？', opts: ['吸积盘外缘', '光也无法从内部逃出的边界', '暗物质边界', '银河系边缘'], ans: 1, explanation: '事件视界以内的逃逸速度大于光速,信息无法逃逸。' },
  { id: 'ap-easy-004', topic: 'astrophysics', difficulty: 'easy', q: '"引力"在牛顿力学中表现为？', opts: ['排斥力', '与质量乘积成正比、距离平方反比的吸引力', '匀速', '随机'], ans: 1, explanation: '万有引力 F = G m1 m2 / r²。' },
  { id: 'ap-easy-005', topic: 'astrophysics', difficulty: 'easy', q: '爱因斯坦质能方程是？', opts: ['F=ma', 'E=mc²', 'V=IR', 'PV=nRT'], ans: 1, explanation: 'E=mc² 表明质量与能量等价,核反应能量来源关键公式。' },
  { id: 'ap-easy-006', topic: 'astrophysics', difficulty: 'easy', q: '"狭义相对论"主要描述？', opts: ['量子粒子', '高速运动惯性系下时空与能量行为', '化学反应', '生物进化'], ans: 1, explanation: '1905年爱因斯坦提出,适用惯性参考系。' },
  { id: 'ap-easy-007', topic: 'astrophysics', difficulty: 'easy', q: '"广义相对论"将引力描述为？', opts: ['粒子交换', '时空弯曲的几何效应', '电磁波', '虚无'], ans: 1, explanation: '质量-能量弯曲时空,物体沿测地线运动。' },
  { id: 'ap-easy-008', topic: 'astrophysics', difficulty: 'easy', q: '"哈勃-勒梅特定律"暗示宇宙处于什么状态？', opts: ['静止', '正在膨胀', '坍缩', '稳态'], ans: 1, explanation: '星系普遍退行,且越远越快,提示宇宙整体膨胀。' },
  { id: 'ap-easy-009', topic: 'astrophysics', difficulty: 'easy', q: '"暗物质"的最大特征是什么？', opts: ['强吸光', '不参与电磁相互作用,只通过引力显现', '不存在', '直接可见'], ans: 1, explanation: '暗物质不发光、不吸光,通过引力效应间接观测。' },
  { id: 'ap-easy-010', topic: 'astrophysics', difficulty: 'easy', q: '"奇点"在物理学中通常指？', opts: ['最远恒星', '物理量(密度/曲率)发散的点', '光子', '探测仪器'], ans: 1, explanation: '黑洞中心或大爆炸初始即为经典广义相对论意义下的奇点。' },
  { id: 'ap-easy-011', topic: 'astrophysics', difficulty: 'easy', q: '日常重力是引力效应,但在等效原理下与什么等价？', opts: ['加速运动', '电磁场', '热涨落', '量子隧穿'], ans: 0, explanation: '等效原理:引力与加速参考系局部不可区分。' },
  { id: 'ap-easy-012', topic: 'astrophysics', difficulty: 'easy', q: '"电磁波谱"按波长由短到长大致包括？', opts: ['伽马—X射线—紫外—可见光—红外—微波—射电', '可见光—射电', '只有可见光', '红外—紫外'], ans: 0, explanation: '完整电磁谱涵盖宽广能量,天文学利用全频谱观测。' },
  { id: 'ap-easy-013', topic: 'astrophysics', difficulty: 'easy', q: '可见光波长范围大约是？', opts: ['0-100 nm', '约 380-780 nm', '1-10 μm', '1 mm'], ans: 1, explanation: '人眼可见光约380-780纳米。' },
  { id: 'ap-easy-014', topic: 'astrophysics', difficulty: 'easy', q: '"中微子"的特点是？', opts: ['静止质量大', '极弱相互作用,极易穿透物质', '带电荷强', '寿命短'], ans: 1, explanation: '中微子几乎只参与弱相互作用,可穿透地球。' },
  { id: 'ap-easy-015', topic: 'astrophysics', difficulty: 'easy', q: '"宇宙学红移"现象与什么有关？', opts: ['行星运动', '宇宙整体空间膨胀', '黑洞辐射', '太阳活动'], ans: 1, explanation: '尺度因子增大导致光波长被拉伸。' },

  // ============ 宇宙物理 - 中级 ============
  { id: 'ap-medium-001', topic: 'astrophysics', difficulty: 'medium', q: '"史瓦西半径"对应天体的什么？', opts: ['行星半径', '某质量黑洞事件视界半径 R = 2GM/c²', '银盘半径', '太阳半径'], ans: 1, explanation: '太阳的史瓦西半径约3公里,地球约9毫米。' },
  { id: 'ap-medium-002', topic: 'astrophysics', difficulty: 'medium', q: '霍金辐射的物理本质是？', opts: ['黑洞燃烧', '事件视界附近的量子效应导致黑洞缓慢发出热辐射', '太阳风', '宇宙射线'], ans: 1, explanation: '霍金1974年导出黑洞具有温度,可由量子场论效应缓慢蒸发。' },
  { id: 'ap-medium-003', topic: 'astrophysics', difficulty: 'medium', q: '广义相对论中黑洞的旋转解叫做？', opts: ['克尔解', '史瓦西解', '德西特解', '弗里德曼解'], ans: 0, explanation: '克尔解(Kerr 1963)描述带角动量的黑洞,内部结构远比史瓦西复杂。' },
  { id: 'ap-medium-004', topic: 'astrophysics', difficulty: 'medium', q: '"等效原理"是哪种相对论的基础？', opts: ['狭义相对论', '广义相对论', '量子论', '热力学'], ans: 1, explanation: '等效原理把引力质量与惯性质量等同,启发广义相对论的几何引力观。' },
  { id: 'ap-medium-005', topic: 'astrophysics', difficulty: 'medium', q: 'CMB 温度涨落的尺度约为？', opts: ['10⁻¹', '10⁻⁵', '10⁻²⁰', '1'], ans: 1, explanation: 'CMB 在2.7K 背景下涨落约 10⁻⁵ K 量级,反映原初密度涨落。' },
  { id: 'ap-medium-006', topic: 'astrophysics', difficulty: 'medium', q: '原子核中质子转化为中子的弱过程是？', opts: ['强核力', 'β⁺ 衰变(p → n + e⁺ + νₑ)', '电磁辐射', '光化学'], ans: 1, explanation: '弱相互作用包括 β⁺/β⁻ 衰变与电子俘获。' },
  { id: 'ap-medium-007', topic: 'astrophysics', difficulty: 'medium', q: '"宇宙学常数"由谁最初引入?最初目的是什么?', opts: ['爱因斯坦,为获得静态宇宙', '哈勃,为度量距离', '霍金,为黑洞', '牛顿,为月运动'], ans: 0, explanation: '爱因斯坦 1917 年引入 Λ 维持静态宇宙,哈勃发现膨胀后他称之为"最大错误"。' },
  { id: 'ap-medium-008', topic: 'astrophysics', difficulty: 'medium', q: '宇宙中已观测重子物质大约占总能量密度的？', opts: ['68%', '约 5%', '27%', '99%'], ans: 1, explanation: '约5%重子+27%暗物质+68%暗能量,比例来自普朗克结果。' },
  { id: 'ap-medium-009', topic: 'astrophysics', difficulty: 'medium', q: '"宇宙微波背景偏振"最重要的两个模式称作？', opts: ['E 模与 B 模', 'X 模与 Y 模', '正模与负模', '红与蓝'], ans: 0, explanation: 'E 模主要由密度扰动产生,B 模可能由原初引力波产生。' },
  { id: 'ap-medium-010', topic: 'astrophysics', difficulty: 'medium', q: '"潮汐力"在双星或卫星系统中表现为？', opts: ['整体加速', '不同点上引力差导致拉伸/挤压效应', '电磁辐射', '热辐射'], ans: 1, explanation: '潮汐效应是产生地月潮汐、伊奥火山活动的关键原因。' },
  { id: 'ap-medium-011', topic: 'astrophysics', difficulty: 'medium', q: '"等离子体"的特点是？', opts: ['绝缘体', '电中性但由自由带电粒子主导,具有强电磁响应', '固态', '冷物质'], ans: 1, explanation: '等离子体是宇宙中最普遍物质态,恒星与星际介质多为等离子体。' },
  { id: 'ap-medium-012', topic: 'astrophysics', difficulty: 'medium', q: 'X 射线双星中的"吸积盘"主要发热机制是？', opts: ['核聚变', '黏滞耗散将引力势能转化为热与辐射', '化学燃烧', '宇宙射线'], ans: 1, explanation: '吸积盘内材料在引力中下落,黏滞使势能转化为光辐射。' },
  { id: 'ap-medium-013', topic: 'astrophysics', difficulty: 'medium', q: '关于黑洞,"无毛定理"的内容大致是？', opts: ['黑洞只由质量、电荷、角动量描述', '黑洞有名字', '黑洞具有头发结构', '黑洞无质量'], ans: 0, explanation: '无毛定理:经典稳态黑洞由M、Q、J三个参数完全描述。' },
  { id: 'ap-medium-014', topic: 'astrophysics', difficulty: 'medium', q: '"宇宙微波背景"提供了什么样的窗口？', opts: ['宇宙38万年时的"婴儿照"', '当下宇宙', '太阳邻域', '银心结构'], ans: 0, explanation: 'CMB 来自复合时代,光子退耦后自由传播至今。' },
  { id: 'ap-medium-015', topic: 'astrophysics', difficulty: 'medium', q: '"原初核合成"主要在大爆炸后多长时间完成？', opts: ['前几分钟,合成约25%质量比的氦-4以及微量锂等', '46亿年', '38万年', '今天仍在'], ans: 0, explanation: 'BBN 在第一个3-20分钟内合成轻元素,与观测氦丰度高度一致。' },

  // ============ 宇宙物理 - 高级 ============
  { id: 'ap-hard-001', topic: 'astrophysics', difficulty: 'hard', q: '"霍金温度"公式 T = ℏc³/(8πGMk_B) 表明什么？', opts: ['黑洞质量越大温度越高', '黑洞质量越大温度越低,蒸发越慢', '与质量无关', '与温度无关'], ans: 1, explanation: '小黑洞热,大黑洞冷,寿命与质量立方成正比。' },
  { id: 'ap-hard-002', topic: 'astrophysics', difficulty: 'hard', q: '"贝肯斯坦-霍金熵"与什么成正比？', opts: ['黑洞体积', '事件视界面积/4', '质量平方根', '温度立方'], ans: 1, explanation: 'S = A/(4ℓ_P²),熵正比于视界面积,启示全息原理。' },
  { id: 'ap-hard-003', topic: 'astrophysics', difficulty: 'hard', q: '"黑洞信息悖论"焦点在于？', opts: ['黑洞不存在', '霍金辐射看似纯热,信息丢失与量子幺正性矛盾', '光速变化', '黑洞带电'], ans: 1, explanation: '近年通过纠缠岛(island)等思路研究信息如何在演化中保留。' },
  { id: 'ap-hard-004', topic: 'astrophysics', difficulty: 'hard', q: '"度规张量 g_μν"在广义相对论中描述？', opts: ['物质成分', '时空几何/距离结构', '能量', '角动量'], ans: 1, explanation: '度规张量定义间隔 ds² = g_μν dx^μ dx^ν,是引力场的几何描述。' },
  { id: 'ap-hard-005', topic: 'astrophysics', difficulty: 'hard', q: '"FRW 度规"用于描述什么？', opts: ['行星轨道', '均匀各向同性宇宙学时空', '黑洞', '原子结构'], ans: 1, explanation: 'FRW(Friedmann–Robertson–Walker)度规是标准宇宙学基础。' },
  { id: 'ap-hard-006', topic: 'astrophysics', difficulty: 'hard', q: 'Friedmann 方程描述？', opts: ['宇宙尺度因子 a(t) 随时间演化与能量密度的关系', '行星轨道', '原子能级', '光速变化'], ans: 0, explanation: '由广义相对论与FRW度规推出,是宇宙学动力学方程。' },
  { id: 'ap-hard-007', topic: 'astrophysics', difficulty: 'hard', q: '"罗伯逊测试"或更广义的"广义相对论检验"在太阳系尺度的经典三大测试包括？', opts: ['水星近日点进动、光线弯曲、引力红移', '行星轨道、月相、彗星', '日食、潮汐、磁暴', '中子星、白矮星、超新星'], ans: 0, explanation: '三大经典验证后续又增加雷达回波延迟(夏皮罗)等。' },
  { id: 'ap-hard-008', topic: 'astrophysics', difficulty: 'hard', q: '"克尔黑洞"的能层(ergosphere)允许什么过程？', opts: ['彭罗斯过程从黑洞角动量提取能量', '光子静止', '霍金辐射加快', '没有特别意义'], ans: 0, explanation: '彭罗斯过程在能层内利用旋转能,有理论意义并启发布兰德福德-知南机制。' },
  { id: 'ap-hard-009', topic: 'astrophysics', difficulty: 'hard', q: '广义相对论预言"引力时间膨胀"已经在 GPS 等系统中需要修正,数量级约为？', opts: ['每天数十微秒', '每秒1秒', '每年1年', '不可测'], ans: 0, explanation: 'GPS 卫星较地面每天快约38微秒,需要相对论修正以保证定位精度。' },
  { id: 'ap-hard-010', topic: 'astrophysics', difficulty: 'hard', q: '"宇宙学微扰理论"第一阶物质功率谱主要受什么物理过程影响？', opts: ['暗物质增长、声学振荡、自由流抑制', '太阳活动', '大气湍流', '黑洞辐射'], ans: 0, explanation: '冷暗物质增长、重子声学振荡、热暗物质自由流共同塑造小尺度物质谱。' },
  { id: 'ap-hard-011', topic: 'astrophysics', difficulty: 'hard', q: '"标准模型粒子家族"中,作为弱相互作用媒介的玻色子是？', opts: ['光子', 'W±/Z⁰', '胶子', '希格斯'], ans: 1, explanation: 'W±传递带电流,Z⁰传递中性流,质量约80/91GeV。' },
  { id: 'ap-hard-012', topic: 'astrophysics', difficulty: 'hard', q: '"不稳定真空"假说中,如果希格斯场处于亚稳态,可能演化为？', opts: ['更低能量真空,以光速膨胀的"真真空泡"', '稳定不变', '反物质宇宙', '黑洞'], ans: 0, explanation: '若真空衰变发生,新真空泡以光速扩张,改变物理常数。' },
  { id: 'ap-hard-013', topic: 'astrophysics', difficulty: 'hard', q: '"标准烛光交叉验证"中,"距离阶梯"中下一级常用的是？', opts: ['造父变星 → Ia 型超新星', '行星 → 卫星', 'CMB → 黑洞', '彗星 → 行星'], ans: 0, explanation: '视差→主序拟合→造父变星→Ia 超新星 是经典距离阶梯。' },
  { id: 'ap-hard-014', topic: 'astrophysics', difficulty: 'hard', q: '"AdS/CFT 对偶"在天体物理中的启示之一是？', opts: ['黑洞行星化', '强耦合规范理论可能与某反德西特时空中的引力对偶,启发夸克胶子等离子体研究', '光速变化', '中微子味道'], ans: 1, explanation: 'Maldacena 1997 年提出的对偶启发多种黑洞热力学与流体研究。' },
  { id: 'ap-hard-015', topic: 'astrophysics', difficulty: 'hard', q: '关于引力波,LIGO 首次直接探测的事件 GW150914 来自？', opts: ['两颗中子星合并', '约36 与29 太阳质量黑洞合并', '超新星', '伽马暴'], ans: 1, explanation: 'GW150914 于2015年9月14日探测到双黑洞并合,获2017年诺贝尔奖。' },
];
